spring:
  datasource:
    url: ${DATABASE_URL}?useSSL=false&characterEncoding=UTF-8&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=200
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_ID}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
    database: mysql
  data:
    redis:
      host: 127.0.0.1
      port: 6379

jwt:
  prefix: 'Bearer '
  secret-key: ${JWT_SECRET_KEY}
  access-token-validity-in-seconds: 150
  refresh-token-validity-in-seconds: 259200


open-api:
  urls:
    - https://openapi.gg.go.kr/Genrestrtlunch
    - https://openapi.gg.go.kr/Genrestrtcate
    - https://openapi.gg.go.kr/Genrestrtmovmntcook
  key: ${OPEN_API_KEY}
  type: xml
  size: 1000

